- name: Install the hirte-agent package
  ansible.builtin.package:
    name:
    - hirte-agent

- name: Copy the Hirte Agent configuration file
  ansible.builtin.template:
    src: agent.conf.j2
    dest: /etc/hirte/agent.conf

- name: Copy the HAProxy configuration file
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/conf.d/agent.cfg

- name: Reload the HAProxy Service configuration
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded

- name: Start the Hirte Agent Service
  ansible.builtin.systemd:
    name: hirte-agent.service
    state: started
