- name: Install the bluechi-agent package
  ansible.builtin.package:
    name:
    - bluechi-agent
    - bluechi-selinux

- name: Copy the BlueChi Agent configuration file
  ansible.builtin.template:
    src: agent.conf.j2
    dest: /etc/bluechi/agent.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy the HAProxy configuration file
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/conf.d/bluechi-agent.cfg
    owner: root
    group: root
    mode: '0644'


- name: Reload the HAProxy Service configuration
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded

- name: Start the BlueChi Agent Service
  ansible.builtin.systemd:
    name: bluechi-agent.service
    state: started
