- name: Install packages
  ansible.builtin.package:
    name:
    - hirte-agent
- name: Copy the Hirte Agent configuration file
  ansible.builtin.copy:
    src: agent.conf
    dest: /etc/hirte/agent.conf
- name: Copy the HAProxy configuration file
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
- name: Allow HAProxy to open TCP sockets
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true
- name: Start the HAProxy Service
  ansible.builtin.systemd:
    name: haproxy
    state: started
- name: Start the Hirte Manager Service
  ansible.builtin.systemd:
    name: hirte-agent.service
    state: started
