- name: Setup Hirte Manager
  hosts: manager
  become: true
  roles:
  - common
  - manager

- name: Setup Agents
  hosts: agents
  become: true
  roles:
  - common
  - agent


  # - name: Generate certificates and create podman secrets for them
  #   block:
  #   - name: Create a temporary directory
  #     ansible.builtin.tempfile:
  #       state: directory
  #       suffix: hirte
  #     register: scratch_dir

  #   - set_fact:
  #       secret_ca_passphrase: "{{ lookup('community.general.random_string') }}"

  #   - name: Generate the CA certificate
  #     include_tasks: "tasks/generate_ca.yml"

  #   - name: Generate the CA certificate
  #     include_tasks: "tasks/generate_certs_secrets.yml"
  #     loop:
  #     - name: manager
  #       ip: "172.18.30.2"
  #     - name: agent
  #       ip: "172.18.30.3"
  #     loop_control:
  #       loop_var: service



