- name: Install the bluechi-controller and bluechi-ctl packages
  ansible.builtin.package:
    name:
    - bluechi-controller
    - bluechi-ctl
    - bluechi-selinux

- name: Copy the BlueChi socket unit file
  ansible.builtin.copy:
    src: bluechi-controller.socket
    dest: /usr/lib/systemd/system/bluechi-controller.socket
    owner: root
    group: root
    mode: '0644'

- name: Copy the BlueChi Manager configuration file
  ansible.builtin.template:
    src: bluechi-controller.conf.j2
    dest: /etc/bluechi/controller.conf.d/allowed_list.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy the HAProxy configuration file
  ansible.builtin.copy:
    src: haproxy.cfg
    dest: /etc/haproxy/conf.d/bluechi-controller.cfg
    owner: root
    group: root
    mode: '0644'

- name: Run daemon reload to so changes to the socket file take affect
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start the BlueChi Manager Socket
  ansible.builtin.systemd:
    name: bluechi-controller.socket
    state: started
    enabled: true

- name: Reload the HAProxy Service configuration
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded
