- name: Install packages
  ansible.builtin.package:
    name:
    - hirte
    - hirte-ctl
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
- name: Set the hirte executable's SELinux label
  community.general.sefcontext:
    target: /usr/bin/hirte
    setype: init_exec_t
    state: present
- name: Copy the Hirte socket unit file
  ansible.builtin.copy:
    src: hirte.socket
    dest: /usr/lib/systemd/system/hirte.socket
- name: Copy the Hirte Manager configuration file
  ansible.builtin.copy:
    src: hirte.conf
    dest: /etc/hirte/hirte.conf
- name: Copy the HAProxy configuration file
  ansible.builtin.copy:
    src: haproxy.cfg
    dest: /etc/haproxy/conf.d/manager.cfg
- name: Allow HAProxy to open TCP sockets
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true
- name: Run daemon reload to so changes to the socket file take affect
  ansible.builtin.systemd:
    daemon_reload: yes
- name: Start the Hirte Manager Service
  ansible.builtin.systemd:
    name: hirte.socket
    state: started
- name: Start the HAProxy Service
  ansible.builtin.systemd:
    name: haproxy
    state: started
