- name: Install the hirte and hirte-ctl packages
  ansible.builtin.package:
    name:
    - hirte
    - hirte-ctl
    - hirte-selinux

- name: Copy the Hirte socket unit file
  ansible.builtin.copy:
    src: hirte.socket
    dest: /usr/lib/systemd/system/hirte.socket
    owner: root
    group: root
    mode: '0644'

- name: Copy the Hirte Manager configuration file
  ansible.builtin.template:
    src: hirte.conf.j2
    dest: /etc/hirte/hirte.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy the HAProxy configuration file
  ansible.builtin.copy:
    src: haproxy.cfg
    dest: /etc/haproxy/conf.d/manager.cfg
    owner: root
    group: root
    mode: '0644'

- name: Allow HAProxy to listen on tcp port 2021
  community.general.seport:
    ports: 2021
    proto: tcp
    setype: http_port_t
    state: present

- name: Run daemon reload to so changes to the socket file take affect
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start the Hirte Manager Service
  ansible.builtin.systemd:
    name: hirte.socket
    state: started

- name: Reload the HAProxy Service configuration
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded
